(function(){
  'use strict';
  const root=document.getElementById('cre-studio');if(!root)return;
  const M=window.CRE,$=s=>root.querySelector(s),$$=s=>Array.from(root.querySelectorAll(s));
  const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n),num=n=>new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(n);
  const date=s=>new Date(s+'T12:00:00Z').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'});
  let selected='florist',activePage='property',activeView='scene',sceneFrame=null,sceneObserver=null,scenario=structuredClone(M.defaults);
  const scenePath=root.dataset.sceneUrl||'',sceneURLs=new Map();let sceneTemplate=null;
  const summary=M.summary();
  const fact=(k,v,cls='')=>`<div class="${cls}"><dt>${k}</dt><dd>${v}</dd></div>`;
  const stat=(label,value,note,cls='')=>`<div class="stat ${cls}"><span>${label}</span><strong>${value}</strong><small>${note}</small></div>`;
  $('#property-stats').innerHTML=stat('Rentable area',num(summary.area)+' SF','Six ground-floor premises')+stat('Occupied premises','6 / 6','Contractual snapshot')+stat('Annual base rent',money(summary.base),'Before expense recoveries')+stat('Annual operating NOI',money(summary.noi),'Before capital and debt costs');
  $('#premise-select').innerHTML=M.premises.map(p=>`<option value="${p.id}">${p.unit} · ${p.name} — ${p.use}</option>`).join('');
  $('#plan-units').innerHTML=M.premises.map(p=>{const w=p.angle?p.d:p.w,d=p.angle?p.w:p.d;return `<button type="button" class="plan-unit" data-id="${p.id}" data-analytics-action="premise_select" data-analytics-value="${p.id}" aria-pressed="false" aria-label="Premise ${p.unit}, ${p.name}, ${p.area} square feet. View lease." style="left:${(p.x-w/2+20)/40*100}%;top:${(p.z-d/2+16)/36*100}%;width:${w/40*100}%;height:${d/36*100}%"><small>${p.unit}</small><b>${p.name}</b><span>${num(p.area)} SF</span></button>`;}).join('');
  function select(id){const p=M.premises.find(p=>p.id===id);if(!p)return;selected=id;$('#premise-select').value=id;$$('.plan-unit').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.id===id)));$('#unit-number').textContent='UNIT '+p.unit;$('#lease-title').textContent=p.name;$('#lease-use').textContent=p.use;$('#lease-facts').innerHTML='<dl>'+fact('Rentable area',num(p.area)+' SF')+fact('Base rent',money(p.rent)+' / SF / year')+fact('Lease expires',date(p.expiry))+fact('Frontage',p.frontage)+'</dl>';$('#lease-base').textContent=money(p.area*p.rent);$('#lease-terms').innerHTML=fact('Lease commencement',date(p.start))+fact('Annual increase',(p.bump*100).toFixed(1)+'% · January 1')+fact('Expense basis',p.recovery)+fact('Annual recoveries',money(M.recovery(p)))+fact('Monthly base + recovery',money((p.rent*p.area+M.recovery(p))/12));$('#premise-note').textContent=p.note;$('#visit-unit').textContent='Visit '+p.name;}
  function showPage(page){if(!['property','leases','activity','assumptions','rendering'].includes(page))return;activePage=page;$$('[data-panel]').forEach(p=>p.hidden=p.dataset.panel!==page);$$('[data-page]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.page===page)));if(page!=='property')suspendScene(true);else suspendScene(activeView!=='scene');}
  function suspendScene(value){const d=sceneFrame?.contentDocument?.getElementById('ame-district')?.__district;if(d?.setSuspended)d.setSuspended(value);}
  function graphicsQuality(){return $('#scene-quality').value==='full'?'full':'balanced';}
  function sceneDocument(quality){if(sceneTemplate===null){const payload=document.getElementById('cre-scene-source');if(!payload)return null;sceneTemplate=JSON.parse(payload.textContent);}return sceneTemplate.replace('window.AME_STUDIO_CONFIG={quality:"balanced"}',`window.AME_STUDIO_CONFIG={quality:"${quality}"}`);}
  function sceneURL(quality){if(scenePath){const url=new URL(scenePath,document.baseURI);url.searchParams.set('quality',quality);return url.href;}if(!sceneURLs.has(quality)){const doc=sceneDocument(quality);if(!doc)return null;sceneURLs.set(quality,URL.createObjectURL(new Blob([doc],{type:'text/html;charset=utf-8'})));}return sceneURLs.get(quality);}
  function prepareSceneLink(){const url=sceneURL(graphicsQuality());if(url)$('#open-scene-tab').href=url;return url;}
  function releaseScene(){sceneObserver?.disconnect();sceneObserver=null;suspendScene(true);sceneFrame?.remove();sceneFrame=null;$('#visit-unit').disabled=true;}
  function sceneUnavailable(){showView('plan');$('#scene-notice').textContent='The 3-D map could not open in this browser. The leasing plan and all financial activities are available. You can try Explore 3-D Map again.';$('#scene-notice').hidden=false;}
  function buildScene(){
    if(sceneFrame)return;
    const quality=graphicsQuality(),doc=scenePath?null:sceneDocument(quality);
    if(!scenePath&&!doc){sceneUnavailable();return;}
    const frame=document.createElement('iframe');sceneFrame=frame;frame.title='Ame Quarter interactive 3-D district';frame.loading='lazy';frame.setAttribute('allow','fullscreen');$('#visit-unit').disabled=true;
    if(scenePath)frame.src=sceneURL(quality);else frame.srcdoc=doc;
    frame.addEventListener('load',()=>{
      if(sceneFrame!==frame)return;
      const district=frame.contentDocument?.getElementById('ame-district');
      if(!district){sceneUnavailable();return;}
      const check=()=>{
        if(sceneFrame!==frame)return;
        if(district.dataset.sceneStatus==='unavailable'){sceneUnavailable();return;}
        if(district.dataset.sceneStatus==='ready'){$('#visit-unit').disabled=false;suspendScene(activePage!=='property'||activeView!=='scene');}
      };
      sceneObserver?.disconnect();sceneObserver=new MutationObserver(check);sceneObserver.observe(district,{attributes:true,attributeFilter:['data-scene-status']});check();
    });
    frame.addEventListener('error',()=>{if(sceneFrame===frame)sceneUnavailable();});
    $('#scene-host').replaceChildren(frame);prepareSceneLink();
  }
  function showView(view){if(!['plan','scene'].includes(view))return;activeView=view;$('#scene-notice').hidden=true;$('#plan-wrap').hidden=view!=='plan';$('#scene-wrap').hidden=view!=='scene';$$('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===view)));$('#property-view-title').textContent=view==='scene'?'Explore the retail plaza':'Ground-floor leasing plan';$('#property-view-help').textContent=view==='scene'?'Orbit the plaza, tour its shops, or visit the selected premise.':'Select a premise to inspect its lease.';if(view==='scene')buildScene();else releaseScene();}
  function visit(){const scene=sceneFrame?.contentDocument?.getElementById('ame-district'),d=scene?.__district;if(d){d.nav.setMode('walk',d.shops.find(s=>s.id===selected));scene.focus({preventScroll:true});}else $('#visit-unit').textContent='Scene loading · try again shortly';}
  $('#open-scene-tab').addEventListener('click',e=>{if(!prepareSceneLink())e.preventDefault();});
  $$('.plan-unit').forEach(b=>b.addEventListener('click',()=>select(b.dataset.id)));$('#premise-select').addEventListener('change',e=>select(e.target.value));$$('[data-page]').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.page)));$$('[data-view]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));$('#scene-quality').addEventListener('change',()=>{releaseScene();if(activeView==='scene')buildScene();});$('#visit-unit').addEventListener('click',visit);$$('[data-open-activity],#premise-activity').forEach(b=>b.addEventListener('click',()=>{showPage('activity');root.scrollIntoView({behavior:'auto',block:'start'});}));
  $('#rent-roll').innerHTML=M.premises.map(p=>`<tr><td><button type="button" data-lease="${p.id}" data-analytics-action="premise_select" data-analytics-value="${p.id}">${p.unit} · ${p.name}</button><small>${p.use}</small></td><td class="num">${num(p.area)}</td><td class="num">${money(p.rent)}</td><td class="num">${money(p.area*p.rent)}</td><td>${p.recovery}</td><td>${date(p.expiry)}</td></tr>`).join('');
  $('#rent-roll-total').innerHTML=`<tr><td>Total</td><td class="num">${num(summary.area)}</td><td class="num">${money(summary.base/summary.area)} avg.</td><td class="num">${money(summary.base)}</td><td colspan="2">6 occupied premises</td></tr>`;
  $$('[data-lease]').forEach(b=>b.addEventListener('click',()=>{select(b.dataset.lease);showPage('property');showView('plan');$('#premise-select').focus();}));
  const expiry={};M.premises.forEach(p=>expiry[p.expiry.slice(0,4)]=(expiry[p.expiry.slice(0,4)]||0)+p.area);
  $('#expiry-chart').innerHTML=Object.entries(expiry).map(([year,area])=>`<div class="expiry-row"><b>${year}</b><div class="expiry-track"><span style="width:${area/M.totalArea*100}%"></span></div><span class="expiry-value">${num(area)} SF · ${(area/M.totalArea*100).toFixed(1)}%</span></div>`).join('');
  $('#property-income').innerHTML=fact('Base rent',money(summary.base))+fact('+ Expense recoveries',money(summary.recoveries))+fact('− Operating expenses',money(summary.operating))+fact('Operating NOI',money(summary.noi),'total');
  $('#budget-detail').innerHTML=fact('Property taxes',money(M.budget.tax))+fact('Insurance',money(M.budget.insurance))+fact('Common-area maintenance',money(M.budget.cam))+fact('Owner administration',money(M.budget.owner))+fact('Total annual expenses',money(M.operating),'total');
  const fields=[['rent','Starting rent · $ / SF / year','Offered rent at commencement',1],['growth','Annual rent increase · %','Each occupancy anniversary',.5],['downtime','Downtime · months','No rent or recoveries',1],['free','Free base rent · months','Recoveries still payable',1],['ti','Tenant improvements · $ / SF','Landlord payment at occupancy',1],['commission','Leasing commission · %','Scheduled rent before concessions',.5]];
  $('#offer-forms').innerHTML=['renew','replace'].map((key,i)=>`<div class="card"><p class="eyebrow">Offer ${i+1}</p><h3>${i?'Re-lease to a new tenant':'Renew with Midori'}</h3><p class="small muted">${i?'Higher asking rent; more leasing friction.':'An incumbent tenant; lower turnover costs.'}</p><div class="form-grid">${fields.map(([field,label,help,step])=>`<label class="field" for="${key}-${field}"><span>${label}</span><input type="number" id="${key}-${field}" data-analytics-action="assumption_change" data-analytics-once="true" data-analytics-value="${key}-${field}" data-offer="${key}" data-field="${field}" min="${M.rules[field][0]}" max="${M.rules[field][1]}" step="${step}" value="${scenario[key][field]}"><small>${help}</small></label>`).join('')}</div></div>`).join('');
  function readScenario(){let error='';$$('[data-offer],#discount').forEach(input=>{const key=input.dataset.field||'discount',value=input.value.trim()===''?NaN:Number(input.value),[min,max]=M.rules[key];const invalid=!Number.isFinite(value)||value<min||value>max||(['downtime','free'].includes(key)&&!Number.isInteger(value));input.setAttribute('aria-invalid',String(invalid));if(invalid)error=`Enter valid assumptions: ${key} must be ${min}–${max}${['downtime','free'].includes(key)?' whole months':''}.`;else if(input.dataset.offer)scenario[input.dataset.offer][key]=value;else scenario.discount=value;});$('#input-error').hidden=!error;$('#input-error').textContent=error;$('#comparison-results').hidden=!!error;$('#cash-flow').closest('.card').hidden=!!error;return !error;}
  function updateComparison(){if(!readScenario())return;const c=M.compare(scenario),same=Math.abs(c.delta)<.005,winner=same?'Equivalent NPV':c.delta>0?'Re-lease leads':'Renewal leads';$('#comparison-results').innerHTML='<div class="result-grid">'+stat('Renewal · 5-year NPV',money(c.renew.npv),'Net of TI and commissions')+stat('Re-lease · 5-year NPV',money(c.replace.npv),'Net of vacancy and leasing costs')+stat(winner,money(Math.abs(c.delta)),same?'At the entered assumptions':'NPV advantage at January 1, 2028','delta')+'</div><p class="result-note">'+(same?'The two offers have the same modeled NPV.':`${c.delta>0?'Re-leasing':'Renewal'} produces ${money(Math.abs(c.delta))} more present value under these assumptions.`)+' Compare the result with tenant credit and the evidence behind the offered rent.</p>';$('#cash-flow').innerHTML=c.renew.rows.map((r,i)=>{const n=c.replace.rows[i];return `<tr><th scope="row">${r.year}</th>${[r.noi,r.leasing,r.cash,n.noi,n.leasing,n.cash].map(v=>`<td class="num">${money(v)}</td>`).join('')}</tr>`;}).join('');}
  $$('[data-offer],#discount').forEach(input=>input.addEventListener('input',updateComparison));
  $('#reset-offers').addEventListener('click',()=>{scenario=structuredClone(M.defaults);$$('[data-offer]').forEach(i=>i.value=scenario[i.dataset.offer][i.dataset.field]);$('#discount').value=scenario.discount;updateComparison();});
  function csv(rows){return rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\r\n');}
  function download(name,rows){const blob=new Blob(['\ufeff'+csv(rows)],{type:'text/csv;charset=utf-8;'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;root.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  $('#export-roll').addEventListener('click',()=>download('ame-quarter-rent-roll.csv',[['Ame Quarter — hypothetical rent roll','As of 2027-01-01'],['Unit','Tenant','Use','Rentable SF','Annual rent per SF USD','Annual base rent USD','Annual recoveries USD','Annual increase percent','Lease start','Lease expiration','Recovery basis'],...M.premises.map(p=>[p.unit,p.name,p.use,p.area,p.rent,p.area*p.rent,M.recovery(p),(p.bump*100).toFixed(2),p.start,p.expiry,p.recovery]),['Total','','',summary.area,'',summary.base,summary.recoveries],['Property operating expenses USD',summary.operating],['Property operating NOI USD',summary.noi]]));
  select(selected);updateComparison();showView('scene');
  root.__studio={select,showPage,showView,get selected(){return selected;},get scenario(){return structuredClone(scenario);},get activePage(){return activePage;},get activeView(){return activeView;}};
})();

